name: REST Assured Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run REST Assured tests
    runs-on: ubuntu-latest
    
    steps:

     
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Change directory to DemoQA and install dependencies
        run: |
          
          npm install
      - name: Run Nightwatch tests
        run: |
          
          node nightwatch.conf.js
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
         name: nightwatch-test-results
         path: DemoQA/test-results 
