name: REST Assured Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run REST Assured tests
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
         #node-version: $undefined
         cache: 'npm'

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: npm-install
        run: |
        
          npm ci

      - name: Install xvfb
        run: |
          sudo apt-get update
          sudo apt-get install xvfb

      - name: Run Nightwatch tests
        run: |
         
          xvfb-run --auto-servernum npm test -- --env chrome
